import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

export default function Restaurant() {
  const router = useRouter();
  const restaurantId = router.query.id ? String(router.query.id) : "";
  const restaurant = api.restaurant.getById.useQuery({ id: restaurantId });

  if (!restaurant.data) {
    return null;
  }

  return (
    <>
      <Head>
        <title>{restaurant.data.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {restaurant.data.name}
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
        </div>
      </main>
    </>
  );
}
